services:
  postgres:
    image: postgres:16
    container_name: pricelyt_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pricelyt_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    logging:
      driver: journald

  migrate:
    image: postgres:16
    depends_on:
      - postgres
    volumes:
      - ./migrations:/migrations
    environment:
      PGPASSWORD: postgres
    command: >
      bash -c "
      for f in /migrations/*.sql; do
        echo Running $$f;
        psql -h postgres -U postgres -d pricelyt_db -f $$f;
      done
      "
    restart: "no"
    logging:
      driver: journald

  scraper:
    build: ./backend/worker-python/scraper
    volumes:
      - ./backend/worker-python/scraper:/app
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/pricelyt_db
    depends_on:
      - migrate
    restart: unless-stopped

    tmpfs:
      - /tmp
      - /var/tmp

    logging:
      driver: journald

volumes:
  pgdata:
