version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: pricelyt_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pricelyt_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  worker1:
    build: ./backend/worker-python
    container_name: pricelyt_worker_1
    environment:
      WORKER_ID: "1"
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/pricelyt_db
    ports:
      - "8001:8000"
    depends_on:
      - postgres

  worker2:
    build: ./backend/worker-python
    container_name: pricelyt_worker_2
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/pricelyt_db
      WORKER_ID: "2"
    ports:
      - "8002:8000"
    depends_on:
      - postgres

volumes:
  pgdata:
