services:
  postgres:
    image: postgres:16
    container_name: pricelyt_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pricelyt_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  scraper:
    build: ./backend/worker-python/scraper
    volumes:
      - ./backend/worker-python/scraper:/app
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/pricelyt_db
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pgdata:
